import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Design System Colors
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#5b403f",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        outline: "#8f6f6e",
        "outline-variant": "#e4bebc",
        "surface-tint": "#bb162c",
        primary: "#b7122a",
        "on-primary": "#ffffff",
        "primary-container": "#db313f",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb3b1",
        secondary: "#635d5d",
        "on-secondary": "#ffffff",
        "secondary-container": "#eae0e0",
        "on-secondary-container": "#696363",
        tertiary: "#5c5c53",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#75756b",
        "on-tertiary-container": "#fffdf0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001c",
        "secondary-fixed": "#eae0e0",
        "secondary-fixed-dim": "#cdc4c4",
        "on-secondary-fixed": "#1f1b1b",
        "on-secondary-fixed-variant": "#4b4546",
        "tertiary-fixed": "#e4e3d6",
        "tertiary-fixed-dim": "#c8c7bb",
        "on-tertiary-fixed": "#1b1c15",
        "on-tertiary-fixed-variant": "#47473e",
        background: "#fcf9f8",
        "on-background": "#1b1c1c",
        "surface-variant": "#e4e2e1",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        "pill": "9999px",
      },
      boxShadow: {
        "warm": "0 12px 30px rgba(183, 18, 42, 0.08)",
      },
    },
  },
  plugins: [],
};
export default config;
